### PR TITLE
Convert Avro-PHP to PSR-Compliant Project

### PR DESCRIPTION
**Pull request by atierant**
What about a little refresh ? :smiley: 
I still have 3 tests which can't pass, but I hope you'll help me to investigate.
 Also, I noticed 5 missing functions on Avro/Datum/AvroIODatumReader :  
skip_array, skip_map, skip_union, skip_enum & skip_fixed

### CODE REVIEW

**Comment by atierant** [comment]
cf. https://gerrit.wikimedia.org/r/#/c/avro-php/+/466838/ for submission

**Comment by gquemener** [comment]
Be careful, you are modifying execution permission on all files. You probably don't want your php classes to be executable. I would suggest switching `chmod 644` everything back!

**Comment by devrck** [comment]
Very nice effort @atierant can't wait to see it in master :+1: .

**Comment by hotrush** [comment]
> Very nice effort @atierant can't wait to see it in master 👍, when do you think you will finish?

seems never :)

**Comment by atierant** [comment]
Sorry, it is in the planning stage but I have a lack of time ...

**Comment by atierant** [comment]
Already done in Gerrit, but not merged... https://gerrit.wikimedia.org/r/#/c/avro-php/+/466838/

**Pull request closed without merging**
